In [1]:
import pandas as pd
import numpy as np

from sklearn import model_selection
from sklearn import  metrics
from statsmodels.formula.api import ols

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

# Zadanie
Proszę pobrać dane z https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
names = ['symboling','normalized-losses','make','fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']

In [3]:
data = pd.read_csv(url, names=names, delimiter=",", na_values=["?"])
print(data.shape)

(205, 26)

In [4]:
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

# Zadanie
Proszę usunąć kolumny, które nie są numeyczne.

In [5]:
drop_list = ['symboling','make','make','fuel-type', 'aspiration', 'num-of-doors', 
             'body-style', 'drive-wheels', 'engine-location','engine-type','num-of-cylinders','fuel-system']

In [6]:
data=data.drop(drop_list, axis=1)
data.head()

,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,NaN,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

# Zadanie
Prosze usunąć brakujące dane.

In [7]:
null_counts = data.isnull().sum()
print("Number of null values in each column:\n{}".format(null_counts))

Number of null values in each column:
normalized-losses    41
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-size           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [8]:
data=data.dropna()
data.head()

,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

In [9]:
data.columns  = [i.replace("-","_") for i in data.columns.values  ]

In [10]:
data.head()

,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

# Zadanie
Proszę nauczyć wszytkie poznane modele regresji.
Który z nich działa najlepiej?

In [11]:
auto_target = data["price"]
auto_data = data.drop(["price"],axis=1)

In [12]:
auto_data.head()

,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29

In [13]:
auto_target.head()

3     13950.0
4     17450.0
6     17710.0
8     23875.0
10    16430.0
Name: price, dtype: float64

In [14]:
y=auto_target
X=auto_data

In [15]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
X_train = X[:-30]
X_test = X[-30:]
 
y_train = y[:-30]
y_test = y[-30:]

In [17]:
train=pd.DataFrame(data[:-30])
train.columns = data.columns.values
train.head()

,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
3,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
6,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
8,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
10,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.8,8.8,101.0,5800.0,23,29,16430.0

In [18]:
test=pd.DataFrame(data[-30:])

In [19]:
model = ols("price ~ curb_weight * width * engine_size * np.log(length) * np.log(wheel_base) * np.log(highway_mpg) * np.log(city_mpg)", data).fit()
# Print the summary
print((model.summary2()))

                                                                      Results: Ordinary least squares
===========================================================================================================================================================================
Model:                                                  OLS                                                Adj. R-squared:                                       0.982
Dependent Variable:                                     price                                              AIC:                                                  2636.3197
Date:                                                   2022-04-27 20:31                                   BIC:                                                  2910.0101
No. Observations:                                       160                                                Log-Likelihood:                                       -1229.2
Df Model:                                               88                                                 F-statistic:                                          99.23
Df Residuals:                                           71                                                 Prob (F-statistic):                                   9.28e-53
R-squared:                                              0.992                                              Scale:                                                6.2102e+05
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                         Coef.       Std.Err.      t    P>|t|      [0.025         0.975]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                                                               17834.3649   16839.7724  1.0591 0.2932    -15743.1877    51411.9175
curb_weight                                                                                          -3747899.0153 1809999.8597 -2.0707 0.0420  -7356936.2307  -138861.8000
width                                                                                                 -347111.8895  913677.6886 -0.3799 0.7051  -2168933.4567  1474709.6777
curb_weight:width                                                                                       -4273.5567  391721.4081 -0.0109 0.9913   -785343.8603   776796.7469
engine_size                                                                                             22142.5311  442764.8094  0.0500 0.9603   -860705.4238   904990.4861
curb_weight:engine_size                                                                              -2785596.6620 1161041.4000 -2.3992 0.0191  -5100647.4607  -470545.8632
width:engine_size                                                                                     8180857.1793 4828422.7062  1.6943 0.0946  -1446744.2510 17808458.6095
curb_weight:width:engine_size                                                                           39617.4775   17321.5329  2.2872 0.0252      5079.3218    74155.6332
np.log(length)                                                                                         137568.7224  229256.3798  0.6001 0.5504   -319555.5156   594692.9604
curb_weight:np.log(length)                                                                            1815038.5017 1412672.9703  1.2848 0.2030  -1001751.3978  4631828.4011
width:np.log(length)                                                                                  5346100.6870 3845829.6859  1.3901 0.1688  -2322265.9075 13014467.2815
curb_weight:width:np.log(length)                                                                       -15236.1197   64600.1721 -0.2359 0.8142   -144045.2045   113572.9650
engine_size:np.log(length)                                                                             -64173.4087  593215.5550 -0.1082 0.9142  -1247011.6301  1118664.8127
curb_weight:engine_size:np.log(length)                                                                 513846.4472  222559.1314  2.3088 0.0239     70076.1433   957616.7511
width:engine_size:np.log(length)                                                                     -1648297.9594  917348.9519 -1.7968 0.0766  -3477439.8177   180843.8989
curb_weight:width:engine_size:np.log(length)                                                            -7282.1776    3289.9988 -2.2134 0.0301    -13842.2488     -722.1064
np.log(wheel_base)                                                                                     226313.6920  189213.0511  1.1961 0.2356   -150966.4163   603593.8002
curb_weight:np.log(wheel_base)                                                                         168960.6627 1292670.3270  0.1307 0.8964  -2408550.7622  2746472.0875
width:np.log(wheel_base)                                                                             -1803335.0719 4467877.2695 -0.4036 0.6877 -10712029.3199  7105359.1762
curb_weight:width:np.log(wheel_base)                                                                    11399.9103   89362.2635  0.1276 0.8989   -166783.3824   189583.2030
engine_size:np.log(wheel_base)                                                                        -732497.5075  733232.0539 -0.9990 0.3212  -2194520.6982   729525.6831
curb_weight:engine_size:np.log(wheel_base)                                                             614677.0499  248424.4725  2.4743 0.0157    119332.7207  1110021.3792
width:engine_size:np.log(wheel_base)                                                                 -1750158.0686 1052079.6633 -1.6635 0.1006  -3847945.3353   347629.1980
curb_weight:width:engine_size:np.log(wheel_base)                                                        -8755.1205    3720.1359 -2.3534 0.0214    -16172.8607    -1337.3803
np.log(length):np.log(wheel_base)                                                                     2075739.1572  628368.1757  3.3034 0.0015    822808.6010  3328669.7133
curb_weight:np.log(length):np.log(wheel_base)                                                         -267175.5740  278294.7481 -0.9600 0.3403   -822079.5412   287728.3931
width:np.log(length):np.log(wheel_base)                                                               -877465.2024 1060835.7924 -0.8271 0.4109  -2992711.6946  1237781.2897
curb_weight:width:np.log(length):np.log(wheel_base)                                                      1264.9952   14518.7153  0.0871 0.9308    -27684.5009    30214.4913
engine_size:np.log(length):np.log(wheel_base)                                                          431541.8995  241334.3356  1.7881 0.0780    -49665.0983   912748.8972
curb_weight:engine_size:np.log(length):np.log(wheel_base)                                             -113592.9814   47470.1469 -2.3929 0.0194   -208245.7660   -18940.1969
width:engine_size:np.log(length):np.log(wheel_base)                                                    349035.0172  201413.1872  1.7329 0.0874    -52571.4714   750641.5058
curb_weight:width:engine_size:np.log(length):np.log(wheel_base)                                          1612.4323     704.6173  2.2884 0.0251       207.4653     3017.3994
np.log(highway_mpg)                                                                                   -331427.5562  212492.2418 -1.5597 0.1233   -755125.0523    92269.9399
curb_weight:np.log(highway_mpg)                                                                      -3969942.4372 1806981.1832 -2.1970 0.0313  -7572960.5826  -366924.2919
width:np.log(highway_mpg)                                                                            -2006535.5360  931086.8675 -2.1550 0.0346  -3863070.0200  -150001.0520
curb_weight:width:np.log(highway_mpg)                                                                   80996.8153  150479.6867  0.5383 0.5921   -219051.1580   381044.7885
engine_size:np.log(highway_mpg)                                                                        992527.4450 1133429.6629  0.8757 0.3842  -1267467.1138  3252522.0038
curb_weight:engine_size:np.log(highway_mpg)                                                            743108.7872  372380.5514  1.9956 0.0498       603.0566  1485614.5178
width:engine_size:np.log(highway_mpg)                                                                -1488017.5832 1694848.2656 -0.8780 0.3829  -4867449.0412  1891413.8747
curb_weight:width:engine_size:np.log(highway_mpg)                                                      -10933.3264    5608.7328 -1.9493 0.0552    -22116.8220      250.1692
np.log(length):np.log(highway_mpg)                                                                   -1630621.2526  740055.1567 -2.2034 0.0308  -3106249.3238  -154993.1815
curb_weight:np.log(length):np.log(highway_mpg)                                                         634680.7613  537647.9431  1.1805 0.2418   -437358.7889  1706720.3114
width:np.log(length):np.log(highway_mpg)                                                             -2264203.8976 1540040.2859 -1.4702 0.1459  -5334957.0113   806549.2161
curb_weight:width:np.log(length):np.log(highway_mpg)                                                   -13382.8503   25572.9124 -0.5233 0.6024    -64373.7894    37608.0888
engine_size:np.log(length):np.log(highway_mpg)                                                         383384.6296 3357330.8226  0.1142 0.9094  -6310942.8963  7077712.1556
curb_weight:engine_size:np.log(length):np.log(highway_mpg)                                            -138270.0124   70833.3000 -1.9520 0.0549   -279507.6011     2967.5763
width:engine_size:np.log(length):np.log(highway_mpg)                                                   310858.0738  297518.7938  1.0448 0.2996   -282377.5518   904093.6994
curb_weight:width:engine_size:np.log(length):np.log(highway_mpg)                                         2026.6897    1060.2445  1.9115 0.0600       -87.3777     4140.7571
np.log(wheel_base):np.log(highway_mpg)                                                                -653402.4901  620344.7492 -1.0533 0.2958  -1890334.7882   583529.8080
curb_weight:np.log(wheel_base):np.log(highway_mpg)                                                    1039135.5807  578522.8433  1.7962 0.0767   -114406.2056  2192677.3671
width:np.log(wheel_base):np.log(highway_mpg)                                                          1114888.5973 1276234.8364  0.8736 0.3853  -1429851.3901  3659628.5846
curb_weight:width:np.log(wheel_base):np.log(highway_mpg)                                               -20467.9859   33941.5453 -0.6030 0.5484    -88145.5050    47209.5333
engine_size:np.log(wheel_base):np.log(highway_mpg)                                                     792686.8002 2414508.3938  0.3283 0.7436  -4021706.1972  5607079.7976
curb_weight:engine_size:np.log(wheel_base):np.log(highway_mpg)                                        -164045.7875   79158.7990 -2.0724 0.0419   -321883.9499    -6207.6252
width:engine_size:np.log(wheel_base):np.log(highway_mpg)                                               299549.6553  354189.4685  0.8457 0.4005   -406684.0861  1005783.3968
curb_weight:width:engine_size:np.log(wheel_base):np.log(highway_mpg)                                     2416.9912    1194.5483  2.0234 0.0468        35.1295     4798.8528
np.log(length):np.log(wheel_base):np.log(highway_mpg)                                                -2920756.5479 2317890.0061 -1.2601 0.2118  -7542497.9520  1700984.8563
curb_weight:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                     -172012.1358  128517.4404 -1.3384 0.1850   -428268.6337    84244.3621
width:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                            426454.4404  374301.4400  1.1393 0.2584   -319881.4334  1172790.3142
curb_weight:width:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                  3457.5691    5758.9263  0.6004 0.5502     -8025.4037    14940.5419
engine_size:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                     -331720.0700 1042696.4031 -0.3181 0.7513  -2410797.6471  1747357.5072
curb_weight:engine_size:np.log(length):np.log(wheel_base):np.log(highway_mpg)                           30570.8870   15008.3906  2.0369 0.0454       645.0061    60496.7678
width:engine_size:np.log(length):np.log(wheel_base):np.log(highway_mpg)                                -62255.3835   62897.2696 -0.9898 0.3256   -187668.9771    63158.2101
curb_weight:width:engine_size:np.log(length):np.log(wheel_base):np.log(highway_mpg)                      -448.7521     225.1825 -1.9928 0.0501      -897.7533        0.2491
np.log(city_mpg)                                                                                        79339.6908  193763.0000  0.4095 0.6834   -307012.7579   465692.1394
curb_weight:np.log(city_mpg)                                                                         -6810250.4438 3312259.2288 -2.0561 0.0435 -13414707.7642  -205793.1233
width:np.log(city_mpg)                                                                               -1877117.4818  891070.8225 -2.1066 0.0387  -3653862.2383  -100372.7253
curb_weight:width:np.log(city_mpg)                                                                     116051.0563  138866.3962  0.8357 0.4061   -160840.6733   392942.7859
engine_size:np.log(city_mpg)                                                                          -675685.2737 1809238.3501 -0.3735 0.7099  -4283204.0820  2931833.5346
curb_weight:engine_size:np.log(city_mpg)                                                              1115417.6225  371541.4932  3.0021 0.0037    374584.9264  1856250.3185
width:engine_size:np.log(city_mpg)                                                                   -3428535.4219 1310942.8876 -2.6153 0.0109  -6042481.2976  -814589.5462
curb_weight:width:engine_size:np.log(city_mpg)                                                         -15575.8941    5446.4370 -2.8598 0.0056    -26435.7811    -4716.0072
np.log(length):np.log(city_mpg)                                                                        598456.7909  795380.2293  0.7524 0.4543   -987486.3419  2184399.9237
curb_weight:np.log(length):np.log(city_mpg)                                                            579985.2913  697245.1581  0.8318 0.4083   -810282.0671  1970252.6497
width:np.log(length):np.log(city_mpg)                                                                  126063.0278 1260193.1495  0.1000 0.9206  -2386690.7443  2638816.7999
curb_weight:width:np.log(length):np.log(city_mpg)                                                      -11936.0744   23103.9453 -0.5166 0.6070    -58004.0328    34131.8840
engine_size:np.log(length):np.log(city_mpg)                                                          -2714664.1829 3512700.4552 -0.7728 0.4422  -9718789.9574  4289461.5916
curb_weight:engine_size:np.log(length):np.log(city_mpg)                                               -203261.8186   71348.6218 -2.8489 0.0057   -345526.9298   -60996.7074
width:engine_size:np.log(length):np.log(city_mpg)                                                      709396.3980  266538.0742  2.6615 0.0096    177934.5727  1240858.2233
curb_weight:width:engine_size:np.log(length):np.log(city_mpg)                                            2829.5156    1032.2416  2.7411 0.0077       771.2844     4887.7468
np.log(wheel_base):np.log(city_mpg)                                                                   1248343.7643  586089.6431  2.1300 0.0366     79714.2078  2416973.3208
curb_weight:np.log(wheel_base):np.log(city_mpg)                                                       1804974.7452 1109591.0362  1.6267 0.1082   -407486.9421  4017436.4324
width:np.log(wheel_base):np.log(city_mpg)                                                              588343.6902 2043294.9482  0.2879 0.7742  -3485870.7195  4662558.0998
curb_weight:width:np.log(wheel_base):np.log(city_mpg)                                                  -30270.3877   34106.6695 -0.8875 0.3778    -98277.1552    37736.3798
engine_size:np.log(wheel_base):np.log(city_mpg)                                                      -3024044.3716 2514815.8965 -1.2025 0.2332  -8038444.8486  1990356.1055
curb_weight:engine_size:np.log(wheel_base):np.log(city_mpg)                                           -246007.0502   80141.5980 -3.0697 0.0030   -405804.8581   -86209.2424
width:engine_size:np.log(wheel_base):np.log(city_mpg)                                                  796687.2999  300887.7570  2.6478 0.0100    196734.1525  1396640.4473
curb_weight:width:engine_size:np.log(wheel_base):np.log(city_mpg)                                        3437.9553    1182.2697  2.9079 0.0049      1080.5765     5795.3341
np.log(length):np.log(wheel_base):np.log(city_mpg)                                                    7219313.9579 2901076.8774  2.4885 0.0152   1434730.9597 13003896.9561
curb_weight:np.log(length):np.log(wheel_base):np.log(city_mpg)                                        -192222.1725  190458.3626 -1.0093 0.3163   -571985.3614   187541.0163
width:np.log(length):np.log(wheel_base):np.log(city_mpg)                                              -164098.4427  299367.4750 -0.5482 0.5853   -761020.2339   432823.3486
curb_weight:width:np.log(length):np.log(wheel_base):np.log(city_mpg)                                     3616.5053    5671.9692  0.6376 0.5258     -7693.0800    14926.0906
engine_size:np.log(length):np.log(wheel_base):np.log(city_mpg)                                        1049185.2831 1196228.6300  0.8771 0.3834  -1336026.8597  3434397.4259
curb_weight:engine_size:np.log(length):np.log(wheel_base):np.log(city_mpg)                              44929.2559   15333.9391  2.9301 0.0046     14354.2499    75504.2620
width:engine_size:np.log(length):np.log(wheel_base):np.log(city_mpg)                                  -161915.4267   62056.6782 -2.6092 0.0111   -285652.9286   -38177.9248
curb_weight:width:engine_size:np.log(length):np.log(wheel_base):np.log(city_mpg)                         -626.0244     223.3895 -2.8024 0.0065     -1071.4505     -180.5983
np.log(highway_mpg):np.log(city_mpg)                                                                  -192772.3264  697210.7233 -0.2765 0.7830  -1582971.0238  1197426.3709
curb_weight:np.log(highway_mpg):np.log(city_mpg)                                                      3432556.4327 1632015.8116  2.1033 0.0390    178409.3296  6686703.5358
width:np.log(highway_mpg):np.log(city_mpg)                                                            -664059.2141 1370160.3328 -0.4847 0.6294  -3396081.3220  2067962.8939
curb_weight:width:np.log(highway_mpg):np.log(city_mpg)                                                 -55978.9076   50884.2917 -1.1001 0.2750   -157439.3034    45481.4883
engine_size:np.log(highway_mpg):np.log(city_mpg)                                                      3563308.4572 3293010.2569  1.0821 0.2829  -3002767.5034 10129384.4178
curb_weight:engine_size:np.log(highway_mpg):np.log(city_mpg)                                          -304944.7815  110232.8114 -2.7664 0.0072   -524742.7646   -85146.7984
width:engine_size:np.log(highway_mpg):np.log(city_mpg)                                                 689974.8187  409302.5251  1.6857 0.0962   -126151.2365  1506100.8739
curb_weight:width:engine_size:np.log(highway_mpg):np.log(city_mpg)                                       4357.9150    1666.6424  2.6148 0.0109      1034.7245     7681.1055

In [20]:
from sklearn import  metrics
metrics.r2_score(train.price, model.predict(train))

0.9914928391488734

In [21]:
from sklearn import  metrics
metrics.r2_score(test.price, model.predict(test))

0.9929105730182503

In [22]:
X_train
X_test 
y_train
y_test

170    11199.0
171    11549.0
172    17669.0
173     8948.0
174    10698.0
175     9988.0
176    10898.0
177    11248.0
178    16558.0
179    15998.0
180    15690.0
182     7775.0
183     7975.0
184     7995.0
185     8195.0
186     8495.0
187     9495.0
188     9995.0
190     9980.0
194    12940.0
195    13415.0
196    15985.0
197    16515.0
198    18420.0
199    18950.0
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, dtype: float64

In [23]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn import model_selection
from sklearn import datasets, linear_model

In [26]:
seed=123
kfold = model_selection.KFold(n_splits=10)

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(make_pipeline(PolynomialFeatures(degree=2), linear_model.LinearRegression()),
                    param_grid={'polynomialfeatures__degree': [1, 2, 3, 4, 5]},
                    cv=kfold,
                    refit=True)
#make_pipeline(PolynomialFeatures(degree=2), linear_model.LinearRegression()).get_params().keys()
grid.fit(X_train, y_train)
print(grid.best_params_)
print(grid.best_estimator_)

{'polynomialfeatures__degree': 1}
Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(degree=1)),
                ('linearregression', LinearRegression())])

In [27]:
from sklearn import  metrics
metrics.r2_score(y_test , grid.best_estimator_.predict(X_test))

0.756219884513092